const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Bullet,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.Audio.Cnds.IsTagPlaying
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Platform: 0},
	{witch: 0},
	{Bullet: 0},
	{Tree: 0},
	{tree2: 0},
	{Solid: 0},
	{outside: 0},
	{sky: 0},
	{ScrollTo: 0},
	{camera: 0},
	{Mountains: 0},
	{DecorationDestroyer: 0},
	{BGtrees: 0},
	{FrontTrees: 0},
	{cloud1: 0},
	{Cloud2: 0},
	{cloud3: 0},
	{GravityButton: 0},
	{Text: 0},
	{frame: 0},
	{pause: 0},
	{score: 0},
	{Text2: 0},
	{question: 0},
	{restart: 0},
	{twitter: 0},
	{backbutton: 0},
	{facebook: 0},
	{Browser: 0},
	{flappywitch: 0},
	{easy: 0},
	{hard: 0},
	{soundon: 0},
	{Fade: 0},
	{darkness: 0},
	{darkness2: 0},
	{Audio: 0},
	{bestScore: 0},
	{Quit: 0},
	{BestScore: 0},
	{difficulty: 0},
	{start: 0},
	{weather: 0},
	{losing: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	witch: class extends self.ISpriteInstance {},
	Tree: class extends self.ISpriteInstance {},
	tree2: class extends self.ISpriteInstance {},
	outside: class extends self.ISpriteInstance {},
	sky: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	Mountains: class extends self.ISpriteInstance {},
	DecorationDestroyer: class extends self.ISpriteInstance {},
	BGtrees: class extends self.ISpriteInstance {},
	FrontTrees: class extends self.ISpriteInstance {},
	cloud1: class extends self.ISpriteInstance {},
	Cloud2: class extends self.ISpriteInstance {},
	cloud3: class extends self.ISpriteInstance {},
	GravityButton: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	frame: class extends self.ISpriteInstance {},
	pause: class extends self.ISpriteInstance {},
	score: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	question: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {},
	twitter: class extends self.ISpriteInstance {},
	backbutton: class extends self.ISpriteInstance {},
	facebook: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	flappywitch: class extends self.ISpriteInstance {},
	easy: class extends self.ISpriteInstance {},
	hard: class extends self.ISpriteInstance {},
	soundon: class extends self.ISpriteInstance {},
	darkness: class extends self.ISpriteInstance {},
	darkness2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	bestScore: class extends self.ISpriteInstance {},
	Quit: class extends self.ISpriteInstance {}
}